---
- name: Ensure unzip is available
  package:
    state: present
    name: unzip
- debug:
    var: tools
- import_tasks: vault.yml
  when: "'vault' in tools"
- import_tasks: terraform.yml
  when: "'terraform' in tools"
- import_tasks: packer.yml
  when: "'packer' in tools"
