---
# handlers file for vault
- name: "Reload systemd"
  systemd:
    daemon_reload: yes
    state: reloaded
    scope: system
  tags: ['vault']

- name: "Restart vault"
  service:
    name: vault
    state: restarted
  tags: ['vault']
